"""Emit LaTeX tables for the survey manuscript directly from selib's result JSONs —
no hand-typed numbers. Usage:
    python3 scripts/gen_paper_tables.py /path/to/survey/tables
Writes: selib_2d.tex, selib_hier.tex, selib_attr.tex (each a tabular body to \\input).
"""
import json, os, sys

RES = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "results")


def load(name):
    p = os.path.join(RES, name)
    return json.load(open(p)) if os.path.exists(p) else None


def fmt_row(name, vals, best_idx, nd=3):
    cells = []
    for i, v in enumerate(vals):
        s = ("%.*f" % (nd, v)) if isinstance(v, (int, float)) else "--"
        cells.append(("\\textbf{%s}" % s) if i == best_idx else s)
    return name + " & " + " & ".join(cells) + " \\\\"


def best_idx(vals, lower=True):
    fin = [(i, v) for i, v in enumerate(vals) if isinstance(v, (int, float))]
    if not fin:
        return -1
    return (min if lower else max)(fin, key=lambda t: t[1])[0]


def main(outdir):
    os.makedirs(outdir, exist_ok=True)
    C = load("compare_results.json")
    HB = load("hcse_bbm_results.json")
    AT = load("attr_results.json")
    AC = load("attributed_compare.json")

    # ---- 2D: structural entropy reached (free k), lower better ----
    if C:
        meths = ["louvain", "leiden", "infomap", "codeseg", "dedoc", "se_louvain"]
        heads = ["Louvain", "Leiden", "Infomap", "CoDeSEG", "deDoc", "\\selibname{} \\texttt{se\\_louvain}"]
        lines = ["% AUTO-GENERATED by selib scripts/gen_paper_tables.py — do not edit numbers by hand",
                 "\\begin{tabular}{l" + "c" * len(meths) + "}", "\\toprule",
                 "Graph & " + " & ".join(heads) + " \\\\", "\\midrule"]
        for d in C["datasets"]:
            vals = [(C["twod"][d].get(m) or {}).get("se2d") for m in meths]
            lines.append(fmt_row(d.replace("mu", "$\\mu$"), vals, best_idx(vals)))
        lines += ["\\bottomrule", "\\end{tabular}"]
        open(os.path.join(outdir, "selib_2d.tex"), "w").write("\n".join(lines) + "\n")
        print("wrote selib_2d.tex")

    # ---- hierarchical: H^T, lower better (merge original HCSE/BBM) ----
    if C:
        hier = {d: dict(C["hier"].get(d, {})) for d in C["datasets"]}
        if HB:
            for d, row in HB["records"].items():
                hier.setdefault(d, {}).update(row)
        meths = ["se_hier", "se_agglomerative", "bbm", "hcse", "paris", "average", "ward"]
        heads = ["\\selibname{} \\texttt{se\\_hier}", "SE-agglom", "BBM", "HCSE",
                 "Paris", "average", "Ward"]
        lines = ["% AUTO-GENERATED by selib scripts/gen_paper_tables.py",
                 "\\begin{tabular}{l" + "c" * len(meths) + "}", "\\toprule",
                 "Graph & " + " & ".join(heads) + " \\\\", "\\midrule"]
        for d in C["datasets"]:
            vals = [(hier[d].get(m) or {}).get("hd_se") for m in meths]
            lines.append(fmt_row(d.replace("mu", "$\\mu$"), vals, best_idx(vals)))
        lines += ["\\bottomrule", "\\end{tabular}"]
        open(os.path.join(outdir, "selib_hier.tex"), "w").write("\n".join(lines) + "\n")
        print("wrote selib_hier.tex")

    # ---- attributed: NMI (ARI), higher better ----
    if AT:
        meths = ["se_gnn", "DeSE", "LSENet", "louvain", "leiden", "infomap", "spectral"]
        heads = ["\\selibname{} \\texttt{se\\_gnn}", "DeSE", "LSENet",
                 "Louvain", "Leiden", "Infomap", "spectral"]
        lines = ["% AUTO-GENERATED by selib scripts/gen_paper_tables.py",
                 "\\begin{tabular}{l" + "c" * len(meths) + "}", "\\toprule",
                 "Graph & " + " & ".join(heads) + " \\\\", "\\midrule"]
        for d in ("Cora", "Citeseer"):
            row = dict(AT["table"].get(d, {}))
            if AC:
                for m in ("DeSE", "LSENet"):
                    if m in AC["table"].get(d, {}):
                        row[m] = AC["table"][d][m]
            nmis = [(row.get(m) or {}).get("nmi") for m in meths]
            bi = best_idx(nmis, lower=False)
            cells = []
            for i, m in enumerate(meths):
                v = row.get(m) or {}
                if v.get("nmi") is None:
                    cells.append("--"); continue
                s = "%.3f" % v["nmi"]
                if v.get("ari") is not None:
                    s += " (%.3f)" % v["ari"]
                cells.append(("\\textbf{%s}" % s) if i == bi else s)
            lines.append(d + " & " + " & ".join(cells) + " \\\\")
        lines += ["\\bottomrule", "\\end{tabular}"]
        open(os.path.join(outdir, "selib_attr.tex"), "w").write("\n".join(lines) + "\n")
        print("wrote selib_attr.tex")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "tables")
